Improvements about ipconfig command
aura-systems/Aura-Operating-System pull request #156
Opened 2020-12-15 13:57 UTC by geomtech

With this PR, we are able to set an ipv4 for every interface using cidr notation.

Example :
`ipconfig /set eth0 192.168.0.1/24 192.168.0.254`

Also, if we don't need to go on internet or an another network, we can choose do not set a gateway.
Like this : 
`ipconfig /set eth0 192.168.0.1/24`

2020-12-17 01:33 UTC, valentinbreiz approved these changes

2020-12-28 10:30 UTC, geomtech commented
![image](https://user-images.githubusercontent.com/5628290/103208095-1b31ac80-4900-11eb-8901-42de55212b64.png)

2020-12-28 14:11 UTC, valentinbreiz requested changes
Why DNS server address is the same as local ip? It should be the same as gateway no?

![image](https://user-images.githubusercontent.com/18724279/103219761-e6811d80-491e-11eb-93dc-6a9b43a7534e.png)

2021-01-04 21:35 UTC, valentinbreiz approved these changes

2021-01-04 21:54 UTC, merged