Replace CommandPCName
aura-systems/Aura-Operating-System pull request #205
Opened 2021-05-30 04:00 UTC by MasterYuan418

I replaced CommandPCName to CommandPCManager

2021-05-31 12:08 UTC, valentinbreiz requested changes
First fo all, thanks for your work! The idea of only one command to change all computers settings is great but we already have some of yours implemented.

You could try to implement the existing ones in the CommandPCManager (or with a better name the Setting class?).

One setting command with:
- change pc name option
- change keyboard map option (https://github.com/aura-systems/Aura-Operating-System/blob/master/Aura%20Operating%20System/Aura_OS/System/Shell/cmdIntr/c_Console/SetKeyboardMap.cs)

2021-05-31 12:08 UTC, valentinbreiz commented on Aura Operating System/Aura_OS/System/Shell/cmdIntr/CommandPCManager.cs
> +                string t = Time.YearString() + "/" + Time.MonthString() + "/" + Time.DayString();
We already have a "time" command, it can be removed

2021-05-31 12:08 UTC, valentinbreiz commented on Aura Operating System/Aura_OS/System/Shell/cmdIntr/CommandPCManager.cs
> +                Kernel.ComputerName = oldComputerName;
Really necessary?

2021-08-20 09:28 UTC, MasterYuan418 commented
Thanks a lot,I will optimization my code.

2021-08-20 09:29 UTC, closed without merging